version: '3.8'

services:
  server:
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "./certbot/conf:/etc/letsencrypt"
      - "./certbot/www:/var/www/certbot"
      - "./nginx:/etc/nginx/conf.d"
      - "./static/:/var/www"
